/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import app.ComparadorFichaExercicio;
import projeto_gym.pro.Projeto_GYMPRO;
import app.Util;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import fachada.Fachada;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import model.Aluno;
import model.Exercicio;
import model.FichaDeTreino;
import model.FichaExercicio;
import model.Instrutor;
import model.ModeloTabela;

/**
 *
 * @author Insinuante
 */
public class AlunosFichaExercicioJFrame extends javax.swing.JFrame {

    private Aluno aluno;
    private Instrutor instrutor;
    private FichaDeTreino ficha;
    private FichaExercicio fichaExer;
    private ArrayList<FichaExercicio> seg = new ArrayList<>();
    private ArrayList<FichaExercicio> ter = new ArrayList<>();
    private ArrayList<FichaExercicio> qua = new ArrayList<>();
    private ArrayList<FichaExercicio> qui = new ArrayList<>();
    private ArrayList<FichaExercicio> sex = new ArrayList<>();
    private ArrayList<FichaExercicio> sab = new ArrayList<>();
    private ArrayList<FichaExercicio> dom = new ArrayList<>();
    private ArrayList<FichaExercicio> itensEditar = new ArrayList<>();
    private ArrayList<FichaExercicio> itensExcluir = new ArrayList<>();
    private String obj, obs;
    
    
    public AlunosFichaExercicioJFrame(Aluno aluno) {
        this.aluno = aluno;
        ficha = new FichaDeTreino();
        fichaExer = new FichaExercicio();
        ficha.setExercicios(new ArrayList<>());
        
        initComponents();
         jTextFieldNomeProf.setText(Fachada.getInstance().getByFuncionario_IdInstrutor(Fachada.getFuncionarioLogado().getId()).getFuncionario().getNome());
        preencherComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBack = new javax.swing.JPanel();
        jPanelBlue = new javax.swing.JPanel();
        jLabeAlunos = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTabbedPaneAvaliacao = new javax.swing.JTabbedPane();
        jPanelDetalhes = new javax.swing.JPanel();
        jLabePresq = new javax.swing.JLabel();
        jLabeDataInicio = new javax.swing.JLabel();
        jLabeDataReav = new javax.swing.JLabel();
        jLabeProfessor = new javax.swing.JLabel();
        jLabeObservações = new javax.swing.JLabel();
        jLabeObejetivo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextFieldNomeProf = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        dataIniciojDateChooser = new com.toedter.calendar.JDateChooser();
        dataReavjDateChooser = new com.toedter.calendar.JDateChooser();
        jPaneTreino = new javax.swing.JPanel();
        jButtonIncluir12 = new javax.swing.JButton();
        domjCheckBox10 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        sabjCheckBox10 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        sexjCheckBox10 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        quijCheckBox10 = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        quajCheckBox10 = new javax.swing.JCheckBox();
        terjCheckBox10 = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        segjCheckBox10 = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldRepeticoe12 = new javax.swing.JTextField();
        jLabeRepeticoes12 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jSpinnerSerie12 = new javax.swing.JSpinner();
        jLabeSerie12 = new javax.swing.JLabel();
        jComboExercicio = new javax.swing.JComboBox<>();
        jLabeOrdem24 = new javax.swing.JLabel();
        jSpinnerOrdem12 = new javax.swing.JSpinner();
        jLabeOrdem25 = new javax.swing.JLabel();
        jLabeExercicio12 = new javax.swing.JLabel();
        jComboBoxTipoExerc = new javax.swing.JComboBox<>();
        jLabelProcurar1 = new javax.swing.JLabel();
        fichaDiajScrollPane = new javax.swing.JScrollPane();
        testejPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        segundajTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tercajTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        quajTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        quijTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        sexjTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        sabjTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        domjTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        addExercicio = new javax.swing.JLabel();
        excluirExercicio = new javax.swing.JLabel();
        importar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonImprimir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar avaliação física");
        setExtendedState(6);

        jPanelBack.setBackground(new java.awt.Color(255, 255, 255));

        jPanelBlue.setBackground(new java.awt.Color(45, 118, 232));

        jLabeAlunos.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabeAlunos.setForeground(new java.awt.Color(255, 255, 255));
        jLabeAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Inspection_50px.png"))); // NOI18N
        jLabeAlunos.setText(" Ficha Treino");

        javax.swing.GroupLayout jPanelBlueLayout = new javax.swing.GroupLayout(jPanelBlue);
        jPanelBlue.setLayout(jPanelBlueLayout);
        jPanelBlueLayout.setHorizontalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBlueLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabeAlunos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBlueLayout.setVerticalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBlueLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabeAlunos)
                .addGap(28, 28, 28))
        );

        jButtonSalvar.setBackground(new java.awt.Color(45, 118, 232));
        jButtonSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(45, 118, 232));
        jButtonCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jPanelDetalhes.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDetalhes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabePresq.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabePresq.setForeground(new java.awt.Color(45, 118, 232));
        jLabePresq.setText("Prescrição nº");

        jLabeDataInicio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeDataInicio.setForeground(new java.awt.Color(45, 118, 232));
        jLabeDataInicio.setText("Data início");

        jLabeDataReav.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeDataReav.setForeground(new java.awt.Color(45, 118, 232));
        jLabeDataReav.setText("Data reavaliação");

        jLabeProfessor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeProfessor.setForeground(new java.awt.Color(45, 118, 232));
        jLabeProfessor.setText("Professor/Avaliador");

        jLabeObservações.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeObservações.setForeground(new java.awt.Color(45, 118, 232));
        jLabeObservações.setText("Observações");

        jLabeObejetivo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeObejetivo.setForeground(new java.awt.Color(45, 118, 232));
        jLabeObejetivo.setText("Obejetivo");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextFieldNomeProf.setEditable(false);
        jTextFieldNomeProf.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanelDetalhesLayout = new javax.swing.GroupLayout(jPanelDetalhes);
        jPanelDetalhes.setLayout(jPanelDetalhesLayout);
        jPanelDetalhesLayout.setHorizontalGroup(
            jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNomeProf)
                    .addComponent(jTextField3)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                        .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeProfessor)
                            .addComponent(jLabeObservações)
                            .addComponent(jLabeObejetivo))
                        .addGap(15, 15, 15))
                    .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                        .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabePresq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dataIniciojDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jLabeDataInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataReavjDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabeDataReav, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanelDetalhesLayout.setVerticalGroup(
            jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabePresq)
                    .addComponent(jLabeDataInicio)
                    .addComponent(jLabeDataReav))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataIniciojDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(dataReavjDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jLabeProfessor)
                .addGap(12, 12, 12)
                .addComponent(jTextFieldNomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabeObejetivo)
                .addGap(12, 12, 12)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabeObservações)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPaneAvaliacao.addTab("Detalhes", jPanelDetalhes);

        jPaneTreino.setBackground(new java.awt.Color(255, 255, 255));

        jButtonIncluir12.setBackground(new java.awt.Color(45, 118, 232));
        jButtonIncluir12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonIncluir12.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIncluir12.setText("Incluir exercício");
        jButtonIncluir12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluir12ActionPerformed(evt);
            }
        });

        domjCheckBox10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(45, 118, 232));
        jLabel23.setText("Dom");

        sabjCheckBox10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(45, 118, 232));
        jLabel24.setText("Sab");

        sexjCheckBox10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(45, 118, 232));
        jLabel25.setText("Sex");

        quijCheckBox10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(45, 118, 232));
        jLabel26.setText("Qui");

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(45, 118, 232));
        jLabel27.setText("Qua");

        quajCheckBox10.setBackground(new java.awt.Color(255, 255, 255));

        terjCheckBox10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(45, 118, 232));
        jLabel28.setText("Ter");

        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(45, 118, 232));
        jLabel29.setText("Seg");

        segjCheckBox10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(45, 118, 232));
        jLabel30.setText("Ficha:");

        jTextFieldRepeticoe12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldRepeticoe12.setText("10");
        jTextFieldRepeticoe12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRepeticoe12ActionPerformed(evt);
            }
        });

        jLabeRepeticoes12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeRepeticoes12.setForeground(new java.awt.Color(45, 118, 232));
        jLabeRepeticoes12.setText("Repetições");

        jTextField16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });

        jSpinnerSerie12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinnerSerie12.setValue(3);

        jLabeSerie12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeSerie12.setForeground(new java.awt.Color(45, 118, 232));
        jLabeSerie12.setText("Série");

        jComboExercicio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboExercicioActionPerformed(evt);
            }
        });

        jLabeOrdem24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeOrdem24.setForeground(new java.awt.Color(45, 118, 232));
        jLabeOrdem24.setText("Obs.:");

        jSpinnerOrdem12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinnerOrdem12.setValue(1);

        jLabeOrdem25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeOrdem25.setForeground(new java.awt.Color(45, 118, 232));
        jLabeOrdem25.setText("Ordem");

        jLabeExercicio12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeExercicio12.setForeground(new java.awt.Color(45, 118, 232));
        jLabeExercicio12.setText("Exercício");

        jComboBoxTipoExerc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboBoxTipoExerc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abdome", "Aeróbico", "Antebraço", "Bíceps", "Costas", "Glúteo", "Ombro", "Peito", "Perna", "Tríceps" }));
        jComboBoxTipoExerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoExercActionPerformed(evt);
            }
        });

        jLabelProcurar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelProcurar1.setForeground(new java.awt.Color(45, 118, 232));
        jLabelProcurar1.setText("Tipo do exercício");

        testejPanel.setBackground(new java.awt.Color(255, 255, 255));

        segundajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Exercício", "Série", "Rep.", "Obs."
            }
        ));
        segundajTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                segundajTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(segundajTable);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 118, 232));
        jLabel1.setText("Segunda-feira");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 118, 232));
        jLabel2.setText("Terça-feira");

        tercajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Exercício", "Série", "Rep.", "Obs."
            }
        ));
        tercajTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tercajTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tercajTable);

        quajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Exercício", "Série", "Rep.", "Obs."
            }
        ));
        quajTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quajTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(quajTable);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 118, 232));
        jLabel3.setText("Quarta-feira");

        quijTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Exercício", "Série", "Rep.", "Obs."
            }
        ));
        quijTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quijTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(quijTable);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 118, 232));
        jLabel4.setText("Quinta-feira");

        sexjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Exercício", "Série", "Rep.", "Obs."
            }
        ));
        sexjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sexjTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(sexjTable);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 118, 232));
        jLabel5.setText("Sexta-feira");

        sabjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Exercício", "Série", "Rep.", "Obs."
            }
        ));
        sabjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sabjTableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(sabjTable);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 118, 232));
        jLabel6.setText("Sábado");

        domjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Exercício", "Série", "Rep.", "Obs."
            }
        ));
        jScrollPane8.setViewportView(domjTable);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(45, 118, 232));
        jLabel7.setText("Domingo");

        javax.swing.GroupLayout testejPanelLayout = new javax.swing.GroupLayout(testejPanel);
        testejPanel.setLayout(testejPanelLayout);
        testejPanelLayout.setHorizontalGroup(
            testejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testejPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(testejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(testejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(testejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(testejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(testejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(testejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(testejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        testejPanelLayout.setVerticalGroup(
            testejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testejPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(testejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(testejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        fichaDiajScrollPane.setViewportView(testejPanel);

        addExercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Plus Math_16px.png"))); // NOI18N
        addExercicio.setPreferredSize(new java.awt.Dimension(40, 40));
        addExercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addExercicioMouseClicked(evt);
            }
        });

        excluirExercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Trash Can_25px.png"))); // NOI18N
        excluirExercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirExercicioMouseClicked(evt);
            }
        });

        importar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Import_disable25px.png"))); // NOI18N
        importar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importarMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Invisible_25px.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPaneTreinoLayout = new javax.swing.GroupLayout(jPaneTreino);
        jPaneTreino.setLayout(jPaneTreinoLayout);
        jPaneTreinoLayout.setHorizontalGroup(
            jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneTreinoLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneTreinoLayout.createSequentialGroup()
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPaneTreinoLayout.createSequentialGroup()
                                    .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSpinnerOrdem12)
                                            .addComponent(jLabeOrdem25))
                                        .addComponent(jLabeOrdem24))
                                    .addGap(20, 20, 20)
                                    .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPaneTreinoLayout.createSequentialGroup()
                                            .addComponent(jComboExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(addExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabeExercicio12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabeSerie12)
                                        .addComponent(jSpinnerSerie12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(16, 16, 16)
                                    .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldRepeticoe12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabeRepeticoes12)))
                                .addComponent(jTextField16))
                            .addComponent(jComboBoxTipoExerc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(segjCheckBox10))
                        .addGap(30, 30, 30)
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(terjCheckBox10))
                        .addGap(30, 30, 30)
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel27)
                            .addComponent(quajCheckBox10))
                        .addGap(30, 30, 30)
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26)
                            .addComponent(quijCheckBox10))
                        .addGap(30, 30, 30)
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPaneTreinoLayout.createSequentialGroup()
                                .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(sexjCheckBox10))
                                .addGap(30, 30, 30)
                                .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(sabjCheckBox10))
                                .addGap(30, 30, 30)
                                .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(domjCheckBox10)
                                    .addComponent(jLabel23)))
                            .addComponent(jButtonIncluir12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPaneTreinoLayout.createSequentialGroup()
                            .addComponent(jLabelProcurar1)
                            .addGap(487, 487, 487)
                            .addComponent(jLabel30)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(importar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(excluirExercicio))
                        .addComponent(fichaDiajScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPaneTreinoLayout.setVerticalGroup(
            jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneTreinoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(fichaDiajScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelProcurar1)
                        .addComponent(excluirExercicio)
                        .addComponent(importar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneTreinoLayout.createSequentialGroup()
                        .addComponent(jComboBoxTipoExerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeOrdem25)
                            .addComponent(jLabeExercicio12)
                            .addComponent(jLabeSerie12)
                            .addComponent(jLabeRepeticoes12))
                        .addGap(18, 18, 18)
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinnerOrdem12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinnerSerie12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldRepeticoe12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneTreinoLayout.createSequentialGroup()
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(segjCheckBox10)
                            .addComponent(terjCheckBox10)
                            .addComponent(quajCheckBox10)
                            .addComponent(sexjCheckBox10)
                            .addComponent(quijCheckBox10)
                            .addComponent(domjCheckBox10)
                            .addComponent(sabjCheckBox10))))
                .addGap(18, 18, 18)
                .addComponent(jLabeOrdem24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIncluir12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneAvaliacao.addTab("Treino", jPaneTreino);

        jButtonImprimir.setBackground(new java.awt.Color(45, 118, 232));
        jButtonImprimir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonImprimir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.setToolTipText("Salvar");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackLayout = new javax.swing.GroupLayout(jPanelBack);
        jPanelBack.setLayout(jPanelBackLayout);
        jPanelBackLayout.setHorizontalGroup(
            jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPaneAvaliacao, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanelBackLayout.setVerticalGroup(
            jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackLayout.createSequentialGroup()
                .addComponent(jPanelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPaneAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        setSize(new java.awt.Dimension(1017, 741));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jTextField1.getText().isEmpty()){
            projeto_gym.pro.Projeto_GYMPRO.fachada.cadastrarFichaDeTreino(getFicha());
            dispose();
        }else{
            projeto_gym.pro.Projeto_GYMPRO.fachada.editarFichaDeTreino(getFicha());
            dispose();
        }
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        if(!jTextField1.getText().isEmpty())
            this.gerarPDF();
        else
            Mensagem.exibirMensagem("Primeirro termine o cadastro!");
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jButtonIncluir12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluir12ActionPerformed
        if(jTextField1.getText().isEmpty()){
            miniGet();
            preencherTabelas();
        }else{
            segjCheckBox10.setSelected(false);
            terjCheckBox10.setSelected(false);
            quajCheckBox10.setSelected(false);
            quijCheckBox10.setSelected(false);
            sexjCheckBox10.setSelected(false);
            sabjCheckBox10.setSelected(false);
            domjCheckBox10.setSelected(false);
            miniGetEdit();
            preencherTabelas();
        }
    }//GEN-LAST:event_jButtonIncluir12ActionPerformed

    private void jTextFieldRepeticoe12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRepeticoe12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRepeticoe12ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jComboExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboExercicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboExercicioActionPerformed

    private void jComboBoxTipoExercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoExercActionPerformed
        preencherComboBox();
    }//GEN-LAST:event_jComboBoxTipoExercActionPerformed

    private void segundajTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_segundajTableMouseClicked
        
        if(!jTextField1.getText().isEmpty()){
            FichaExercicio fAux = new FichaExercicio();
            String exercicioNome = segundajTable.getValueAt(segundajTable.getSelectedRow(), 0)+"";
            int rep = Integer.parseInt(segundajTable.getValueAt(segundajTable.getSelectedRow(), 2)+""); 
            fAux.setExercicio(Fachada.getInstance().getExercicioNomeExercicio(exercicioNome));
            fAux.setRepeticoes(rep);
            itensEditar=selectLinhas(fAux);
        }
    }//GEN-LAST:event_segundajTableMouseClicked

    private void tercajTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tercajTableMouseClicked
        if(!jTextField1.getText().isEmpty()){
            FichaExercicio fAux = new FichaExercicio();
            String exercicioNome = tercajTable.getValueAt(tercajTable.getSelectedRow(), 0)+"";
            int rep = Integer.parseInt(tercajTable.getValueAt(tercajTable.getSelectedRow(), 2)+""); 
            fAux.setExercicio(Fachada.getInstance().getExercicioNomeExercicio(exercicioNome));
            fAux.setRepeticoes(rep);
            itensEditar=selectLinhas(fAux);
        }
    }//GEN-LAST:event_tercajTableMouseClicked

    private void sexjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sexjTableMouseClicked
            if(!jTextField1.getText().isEmpty()){
            FichaExercicio fAux = new FichaExercicio();
            String exercicioNome = sexjTable.getValueAt(sexjTable.getSelectedRow(), 0)+"";
            int rep = Integer.parseInt(sexjTable.getValueAt(sexjTable.getSelectedRow(), 2)+""); 
            fAux.setExercicio(Fachada.getInstance().getExercicioNomeExercicio(exercicioNome));
            fAux.setRepeticoes(rep);
            itensEditar=selectLinhas(fAux);
        }
    }//GEN-LAST:event_sexjTableMouseClicked

    private void quajTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quajTableMouseClicked
        if(!jTextField1.getText().isEmpty()){
            FichaExercicio fAux = new FichaExercicio();
            String exercicioNome = quajTable.getValueAt(quajTable.getSelectedRow(), 0)+"";
            int rep = Integer.parseInt(quajTable.getValueAt(quajTable.getSelectedRow(), 2)+""); 
            fAux.setExercicio(Fachada.getInstance().getExercicioNomeExercicio(exercicioNome));
            fAux.setRepeticoes(rep);
            itensEditar=selectLinhas(fAux);
        }
    }//GEN-LAST:event_quajTableMouseClicked

    private void quijTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quijTableMouseClicked
        if(!jTextField1.getText().isEmpty()){
            FichaExercicio fAux = new FichaExercicio();
            String exercicioNome = quijTable.getValueAt(quijTable.getSelectedRow(), 0)+"";
            int rep = Integer.parseInt(quijTable.getValueAt(quijTable.getSelectedRow(), 2)+""); 
            fAux.setExercicio(Fachada.getInstance().getExercicioNomeExercicio(exercicioNome));
            fAux.setRepeticoes(rep);
            itensEditar=selectLinhas(fAux);
        }
    }//GEN-LAST:event_quijTableMouseClicked

    private void sabjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sabjTableMouseClicked
        if(!jTextField1.getText().isEmpty()){
            FichaExercicio fAux = new FichaExercicio();
            String exercicioNome = sabjTable.getValueAt(sabjTable.getSelectedRow(), 0)+"";
            int rep = Integer.parseInt(sabjTable.getValueAt(sabjTable.getSelectedRow(), 2)+""); 
            fAux.setExercicio(Fachada.getInstance().getExercicioNomeExercicio(exercicioNome));
            fAux.setRepeticoes(rep);
            itensEditar=selectLinhas(fAux);
        }
    }//GEN-LAST:event_sabjTableMouseClicked

    private void addExercicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addExercicioMouseClicked
       new ExerciciosCadastroJFrame().show();
       preencherComboBox();
    }//GEN-LAST:event_addExercicioMouseClicked

    private void importarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importarMouseClicked
        if(importar.getIcon().toString().equals("src\\imagens\\Import_25px.png")){
            miniGet();
            preencherTabelas();
        }        
    }//GEN-LAST:event_importarMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void excluirExercicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirExercicioMouseClicked
        FichaExercicio fAux = new FichaExercicio();
        String exercicioNome = segundajTable.getValueAt(segundajTable.getSelectedRow(), 0)+"";
        int rep = Integer.parseInt(segundajTable.getValueAt(segundajTable.getSelectedRow(), 2)+""); 
        fAux.setExercicio(Fachada.getInstance().getExercicioNomeExercicio(exercicioNome));
        fAux.setRepeticoes(rep);
        itensExcluir = selectLinhas(fAux);
        
        minigetExcluir(itensExcluir);
        if(itensExcluir.get(0).getId()==0){
            for(FichaExercicio f : itensExcluir)
                Fachada.getInstance().excluirFichaExercicio(f);
        }
        
        preencherTabelas();
    }//GEN-LAST:event_excluirExercicioMouseClicked
   
    private void domjTableMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if(!jTextField1.getText().isEmpty()){
            FichaExercicio fAux = new FichaExercicio();
            String exercicioNome = domjTable.getValueAt(domjTable.getSelectedRow(), 0)+"";
            int rep = Integer.parseInt(domjTable.getValueAt(domjTable.getSelectedRow(), 2)+""); 
            fAux.setExercicio(Fachada.getInstance().getExercicioNomeExercicio(exercicioNome));
            fAux.setRepeticoes(rep);
            itensEditar=selectLinhas(fAux);
        }
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addExercicio;
    private com.toedter.calendar.JDateChooser dataIniciojDateChooser;
    private com.toedter.calendar.JDateChooser dataReavjDateChooser;
    private javax.swing.JCheckBox domjCheckBox10;
    private javax.swing.JTable domjTable;
    private javax.swing.JLabel excluirExercicio;
    private javax.swing.JScrollPane fichaDiajScrollPane;
    private javax.swing.JLabel importar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonIncluir12;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxTipoExerc;
    private javax.swing.JComboBox<String> jComboExercicio;
    private javax.swing.JLabel jLabeAlunos;
    private javax.swing.JLabel jLabeDataInicio;
    private javax.swing.JLabel jLabeDataReav;
    private javax.swing.JLabel jLabeExercicio12;
    private javax.swing.JLabel jLabeObejetivo;
    private javax.swing.JLabel jLabeObservações;
    private javax.swing.JLabel jLabeOrdem24;
    private javax.swing.JLabel jLabeOrdem25;
    private javax.swing.JLabel jLabePresq;
    private javax.swing.JLabel jLabeProfessor;
    private javax.swing.JLabel jLabeRepeticoes12;
    private javax.swing.JLabel jLabeSerie12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelProcurar1;
    private javax.swing.JPanel jPaneTreino;
    private javax.swing.JPanel jPanelBack;
    private javax.swing.JPanel jPanelBlue;
    private javax.swing.JPanel jPanelDetalhes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSpinner jSpinnerOrdem12;
    private javax.swing.JSpinner jSpinnerSerie12;
    private javax.swing.JTabbedPane jTabbedPaneAvaliacao;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldNomeProf;
    private javax.swing.JTextField jTextFieldRepeticoe12;
    private javax.swing.JCheckBox quajCheckBox10;
    private javax.swing.JTable quajTable;
    private javax.swing.JCheckBox quijCheckBox10;
    private javax.swing.JTable quijTable;
    private javax.swing.JCheckBox sabjCheckBox10;
    private javax.swing.JTable sabjTable;
    private javax.swing.JCheckBox segjCheckBox10;
    private javax.swing.JTable segundajTable;
    private javax.swing.JCheckBox sexjCheckBox10;
    private javax.swing.JTable sexjTable;
    private javax.swing.JTable tercajTable;
    private javax.swing.JCheckBox terjCheckBox10;
    private javax.swing.JPanel testejPanel;
    // End of variables declaration//GEN-END:variables

    public FichaDeTreino getFicha(){

        ficha.setData(Util.converterCalendarToDate2(dataIniciojDateChooser.getCalendar()));
        ficha.setDataReavaliacao(Util.converterCalendarToDate2(dataReavjDateChooser.getCalendar()));    
        ficha.setInstrutor(Fachada.getInstance().getByFuncionario_IdInstrutor(
                Fachada.getFuncionarioLogado().getId()));
        ficha.setAluno(aluno);
        ficha.setObg(jTextField3.getText());
        ficha.setObs(jTextArea1.getText());
        ficha.getExercicios().clear();
        
        for(FichaExercicio e : seg)
            ficha.getExercicios().add(e);
        for(FichaExercicio e : ter)
            ficha.getExercicios().add(e);
        
        for(FichaExercicio e : qua)
            ficha.getExercicios().add(e);
        
        for(FichaExercicio e : qui)
            ficha.getExercicios().add(e);
        
        for(FichaExercicio e : sex)
            ficha.getExercicios().add(e);
        
        for(FichaExercicio e : sab)
            ficha.getExercicios().add(e);
        
        for(FichaExercicio e : dom)
            ficha.getExercicios().add(e);
          
        
        return ficha;
    }
    
    public void setFicha(FichaDeTreino f){
        dataIniciojDateChooser.setDate(f.getData());
        dataReavjDateChooser.setDate(f.getDataReavaliacao());
        ficha=f;
        jTextField3.setText(f.getObg());
        jTextArea1.setText(f.getObs());
        jTextFieldNomeProf.setText(f.getInstrutor().getFuncionario().getNome());
        jTextField1.setText(f.getId()+"");
        importar.setIcon(new ImageIcon("src\\imagens\\Import_25px.png"));
        
        for(FichaExercicio e : f.getExercicios()){
            if(e.getDia().equals("segunda"))
                seg.add(e);
            if(e.getDia().equals("terça"))
                ter.add(e);
            if(e.getDia().equals("quarta"))
                qua.add(e);
            if(e.getDia().equals("quinta"))
                qui.add(e);
            if(e.getDia().equals("sexta"))
                sex.add(e);
            if(e.getDia().equals("sabado"))
                sab.add(e);
            if(e.getDia().equals("domingo"))
                dom.add(e);
        }   
        
        Collections.sort(seg,new ComparadorFichaExercicio());
        Collections.sort(ter,new ComparadorFichaExercicio());
        Collections.sort(qua,new ComparadorFichaExercicio());
        Collections.sort(qui,new ComparadorFichaExercicio());
        Collections.sort(sex,new ComparadorFichaExercicio());
        Collections.sort(sab,new ComparadorFichaExercicio());
        Collections.sort(dom,new ComparadorFichaExercicio());
        
        preencherTabelas();
             
    }
    
    public void miniGet(){
        fichaExer.setRepeticoes(Integer.parseInt(jTextFieldRepeticoe12.getText()));
        fichaExer.setOrdem(Integer.parseInt(jSpinnerOrdem12.getValue().toString()));
        fichaExer.setSerie(Integer.parseInt(jSpinnerSerie12.getValue().toString()));
        fichaExer.setExercicio(Fachada.getInstance().getExercicioNomeExercicio(jComboExercicio.getSelectedItem() + ""));
        fichaExer.setObs(jTextField16.getText());

        if(segjCheckBox10.isSelected()){
            seg.add(new FichaExercicio("segunda", fichaExer));
        }

        if(terjCheckBox10.isSelected()){
            ter.add(new FichaExercicio("terça", fichaExer));
        }

        if(quajCheckBox10.isSelected()){
            qua.add(new FichaExercicio("quarta", fichaExer));
        }

        if(quijCheckBox10.isSelected()){
            qui.add(new FichaExercicio("quinta", fichaExer));
        }

        if(sexjCheckBox10.isSelected()){
            sex.add(new FichaExercicio("sexta", fichaExer));
        }

        if(sabjCheckBox10.isSelected()){
            sab.add(new FichaExercicio("sabado", fichaExer));
        }

        if(domjCheckBox10.isSelected()){
            dom.add(new FichaExercicio("domingo", fichaExer));
        }
        
        Collections.sort(seg,new ComparadorFichaExercicio());
        Collections.sort(ter,new ComparadorFichaExercicio());
        Collections.sort(qua,new ComparadorFichaExercicio());
        Collections.sort(qui,new ComparadorFichaExercicio());
        Collections.sort(sex,new ComparadorFichaExercicio());
        Collections.sort(sab,new ComparadorFichaExercicio());
        Collections.sort(dom,new ComparadorFichaExercicio());
    }
    
    public ArrayList<FichaExercicio> minigetExcluir(ArrayList<FichaExercicio> excluir){
                
        for(FichaExercicio fex : excluir){
            int indice=-1;
            if(fex.getDia().equals("segunda")){
                indice = Util.getIndiceByID(seg, fex);
                if(indice!=-1){
                    seg.remove(indice);
                    indice=-1;
                }
            }
            
            if(fex.getDia().equals("terça")){
                indice = Util.getIndiceByID(ter, fex);
                if(indice!=-1){
                    ter.remove(indice);
                    indice=-1;
                }
            }
            if(fex.getDia().equals("quarta")){
                indice = Util.getIndiceByID(qua, fex);
                if(indice!=-1){
                    qua.remove(indice);
                    indice=-1;
                }
            }
            if(fex.getDia().equals("quinta")){
                indice = Util.getIndiceByID(qui, fex);
                if(indice!=-1){
                    qui.remove(indice);
                    indice=-1;
                }
            }
            if(fex.getDia().equals("sexta")){
                indice = Util.getIndiceByID(sex, fex);
                if(indice!=-1){
                    sex.remove(indice);
                    indice=-1;
                }
            }
            if(fex.getDia().equals("sabado")){
                indice = Util.getIndiceByID(sab, fex);
                if(indice!=-1){
                    sab.remove(indice);
                    indice=-1;
                }
            }
            if(fex.getDia().equals("domingo")){
                indice = Util.getIndiceByID(dom, fex);
                if(indice!=-1){
                    dom.remove(indice);
                    indice=-1;
                }
            }
            
        }
        
        return excluir;
    }
    
    public void miniGetEdit(){
        fichaExer.setRepeticoes(Integer.parseInt(jTextFieldRepeticoe12.getText()));
        fichaExer.setOrdem(Integer.parseInt(jSpinnerOrdem12.getValue().toString()));
        fichaExer.setSerie(Integer.parseInt(jSpinnerSerie12.getValue().toString()));
        fichaExer.setExercicio(Fachada.getInstance().getExercicioNomeExercicio(jComboExercicio.getSelectedItem() + ""));
        fichaExer.setObs(jTextField16.getText());
        fichaExer.setFichaDeTreino(Integer.parseInt(jTextField1.getText()));    
        
        for(FichaExercicio fex : itensEditar){
            int indice=-1;
            if(fex.getDia().equals("segunda")){
                indice = Util.getIndiceByID(seg, fex);
                if(indice!=-1){
                    fichaExer.setId(seg.get(indice).getId());
                    fichaExer.setDia("segunda");
                    seg.set(indice,new FichaExercicio(fichaExer));
                    indice=-1;
                }
            }
            
            if(fex.getDia().equals("terça")){
                indice = Util.getIndiceByID(ter, fex);
                if(indice!=-1){
                    fichaExer.setDia("terça");
                    fichaExer.setId(ter.get(indice).getId());
                    ter.set(indice,new FichaExercicio(fichaExer));
                    indice=-1;
                }
            }
            if(fex.getDia().equals("quarta")){
                indice = Util.getIndiceByID(qua, fex);
                if(indice!=-1){
                    fichaExer.setId(qua.get(indice).getId());
                    fichaExer.setDia("quarta");
                    qua.set(indice,new FichaExercicio(fichaExer));
                    indice=-1;
                }
            }
            if(fex.getDia().equals("quinta")){
                indice = Util.getIndiceByID(qui, fex);
                if(indice!=-1){
                    fichaExer.setDia("quinta");
                    fichaExer.setId(qui.get(indice).getId());
                    qui.set(indice,new FichaExercicio(fichaExer));
                    indice=-1;
                }
            }
            if(fex.getDia().equals("sexta")){
                indice = Util.getIndiceByID(sex, fex);
                if(indice!=-1){
                    fichaExer.setDia("sexta");
                    fichaExer.setId(sex.get(indice).getId());
                    sex.set(indice,new FichaExercicio(fichaExer));
                    indice=-1;
                }
            }
            if(fex.getDia().equals("sabado")){
                indice = Util.getIndiceByID(sab, fex);
                if(indice!=-1){
                    fichaExer.setDia("sabado");
                    fichaExer.setId(sab.get(indice).getId());
                    sab.set(indice,new FichaExercicio(fichaExer));
                    indice=-1;
                }
            }
            if(fex.getDia().equals("domingo")){
                indice = Util.getIndiceByID(dom, fex);
                if(indice!=-1){
                    fichaExer.setDia("domingo");
                    fichaExer.setId(dom.get(indice).getId());
                    dom.set(indice,new FichaExercicio(fichaExer));
                    indice=-1;
                }
            }
            
        }
        itensEditar.clear();
        
        Collections.sort(seg,new ComparadorFichaExercicio());
        Collections.sort(ter,new ComparadorFichaExercicio());
        Collections.sort(qua,new ComparadorFichaExercicio());
        Collections.sort(qui,new ComparadorFichaExercicio());
        Collections.sort(sex,new ComparadorFichaExercicio());
        Collections.sort(sab,new ComparadorFichaExercicio());
        Collections.sort(dom,new ComparadorFichaExercicio());
    }
    
    
    
    private void preencherComboBox(){
        ArrayList<Exercicio> e = projeto_gym.pro.Projeto_GYMPRO.fachada.getAllTipoExercicio(
                jComboBoxTipoExerc.getSelectedItem()+"");
        if(e!=null){
            jComboExercicio.removeAllItems();
            for(Exercicio ex : e){
                jComboExercicio.addItem(ex.getNome());
            }
        }
    }
    
    public ArrayList <FichaExercicio> selectLinhas(FichaExercicio f){
        ArrayList <FichaExercicio> linhasSelecionadas = new ArrayList<>();
        segjCheckBox10.setSelected(false);
        terjCheckBox10.setSelected(false);
        quajCheckBox10.setSelected(false);
        quijCheckBox10.setSelected(false);
        sexjCheckBox10.setSelected(false);
        sabjCheckBox10.setSelected(false);
        domjCheckBox10.setSelected(false);
        
        segundajTable.clearSelection();
        tercajTable.clearSelection();
        quajTable.clearSelection();
        quijTable.clearSelection();
        sexjTable.clearSelection();
        sabjTable.clearSelection();
        domjTable.clearSelection();
        
        
        for(int i=0;i<seg.size();i++){
            if(f.getExercicio().getNome().equals(seg.get(i).getExercicio().getNome()) && f.getRepeticoes()==seg.get(i).getRepeticoes()){
                segundajTable.setRowSelectionInterval(i, i);
                linhasSelecionadas.add(seg.get(i));
                segjCheckBox10.setSelected(true);
                
            }
            
        }
        for(int i=0;i<ter.size();i++){
            if(f.getExercicio().getNome().equals(ter.get(i).getExercicio().getNome()) && f.getRepeticoes()==ter.get(i).getRepeticoes()){
                tercajTable.setRowSelectionInterval(i, i);

                linhasSelecionadas.add(ter.get(i));
                terjCheckBox10.setSelected(true);
               
            }
        }
        
        for(int i=0;i<qua.size();i++){
            if(f.getExercicio().getNome().equals(qua.get(i).getExercicio().getNome()) && f.getRepeticoes()==qua.get(i).getRepeticoes()){
                quajTable.setRowSelectionInterval(i, i);
                linhasSelecionadas.add(qua.get(i));
                quajCheckBox10.setSelected(true);
                
            }
        }
        
        for(int i=0;i<qui.size();i++){
            if(f.getExercicio().getNome().equals(qui.get(i).getExercicio().getNome()) && f.getRepeticoes()==qui.get(i).getRepeticoes()){
                quijTable.setRowSelectionInterval(i, i);
                linhasSelecionadas.add(qui.get(i));
                quijCheckBox10.setSelected(true);
                
            }
        }
        
        for(int i=0;i<sex.size();i++){
            if(f.getExercicio().getNome().equals(sex.get(i).getExercicio().getNome()) && f.getRepeticoes()==sex.get(i).getRepeticoes()){
                sexjTable.setRowSelectionInterval(i, i);
                linhasSelecionadas.add(sex.get(i));
                sexjCheckBox10.setSelected(true);
               
            }
        }
        
        for(int i=0;i<sab.size();i++){
            if(f.getExercicio().getNome().equals(sab.get(i).getExercicio().getNome()) && f.getRepeticoes()==sab.get(i).getRepeticoes()){
                sabjTable.setRowSelectionInterval(i, i);
                linhasSelecionadas.add(sab.get(i));
                sabjCheckBox10.setSelected(true);
                
            }
        }
        
        for(int i=0;i<dom.size();i++){
            if(f.getExercicio().getNome().equals(dom.get(i).getExercicio().getNome()) && f.getRepeticoes()==dom.get(i).getRepeticoes()){
                domjTable.setRowSelectionInterval(i, i);
                linhasSelecionadas.add(dom.get(i));
                domjCheckBox10.setSelected(true);
                
            }
        }
        jComboBoxTipoExerc.setSelectedItem(linhasSelecionadas.get(0).getExercicio().getTipo());
        jComboExercicio.setSelectedItem(linhasSelecionadas.get(0).getExercicio().getNome());
        jTextField16.setText(linhasSelecionadas.get(0).getObs());
        jSpinnerOrdem12.setValue(linhasSelecionadas.get(0).getOrdem());
        jSpinnerSerie12.setValue(linhasSelecionadas.get(0).getSerie());
        return linhasSelecionadas;
        
    }
    
    private void preencherTabelas(){
        String[] colunas = new String[]{"Exercício","Série","Rep.","Obs"};
        ArrayList<Object[]> dadosSeg = new ArrayList<>();
        ArrayList<Object[]> dadoster = new ArrayList<>();
        ArrayList<Object[]> dadosqua = new ArrayList<>();
        ArrayList<Object[]> dadosqui = new ArrayList<>();
        ArrayList<Object[]> dadosSex = new ArrayList<>();
        ArrayList<Object[]> dadosSab = new ArrayList<>();
        ArrayList<Object[]> dadosDom = new ArrayList<>();
        for(FichaExercicio f: seg){
            dadosSeg.add(new Object[]{f.getExercicio().getNome(),f.getSerie(),f.getRepeticoes(),f.getObs()});
        }
        
        for(FichaExercicio f: ter){
            dadoster.add(new Object[]{f.getExercicio().getNome(),f.getSerie(),f.getRepeticoes(),f.getObs()});
        }
        
        for(FichaExercicio f: qua){
            dadosqua.add(new Object[]{f.getExercicio().getNome(),f.getSerie(),f.getRepeticoes(),f.getObs()});
        }
        for(FichaExercicio f: qui){
            dadosqui.add(new Object[]{f.getExercicio().getNome(),f.getSerie(),f.getRepeticoes(),f.getObs()});
        }
        
        for(FichaExercicio f: sex){
            dadosSex.add(new Object[]{f.getExercicio().getNome(),f.getSerie(),f.getRepeticoes(),f.getObs()});
        }
        for(FichaExercicio f: sab){
            dadosSab.add(new Object[]{f.getExercicio().getNome(),f.getSerie(),f.getRepeticoes(),f.getObs()});
        }
        for(FichaExercicio f: dom){
            dadosDom.add(new Object[]{f.getExercicio().getNome(),f.getSerie(),f.getRepeticoes(),f.getObs()});
        }
        
        
        ModeloTabela modeloTabela =  new ModeloTabela(dadosSeg, colunas);   
        segundajTable.setModel(modeloTabela);      
        segundajTable.getColumnModel().getColumn(0).setPreferredWidth(55);
        segundajTable.getColumnModel().getColumn(0).setResizable(false);
        segundajTable.getColumnModel().getColumn(1).setPreferredWidth(54);
        segundajTable.getColumnModel().getColumn(1).setResizable(false);
        segundajTable.getColumnModel().getColumn(2).setPreferredWidth(55);
        segundajTable.getColumnModel().getColumn(2).setResizable(false);
        segundajTable.getColumnModel().getColumn(3).setPreferredWidth(55);
        segundajTable.getColumnModel().getColumn(3).setResizable(false);
        segundajTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
          
        tercajTable.setModel(new ModeloTabela(dadoster, colunas));      
        tercajTable.getColumnModel().getColumn(0).setPreferredWidth(55);
        tercajTable.getColumnModel().getColumn(0).setResizable(false);
        tercajTable.getColumnModel().getColumn(1).setPreferredWidth(54);
        tercajTable.getColumnModel().getColumn(1).setResizable(false);
        tercajTable.getColumnModel().getColumn(2).setPreferredWidth(55);
        tercajTable.getColumnModel().getColumn(2).setResizable(false);
        tercajTable.getColumnModel().getColumn(3).setPreferredWidth(55);
        tercajTable.getColumnModel().getColumn(3).setResizable(false);
        tercajTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
           
        quajTable.setModel(new ModeloTabela(dadosqua, colunas));      
        quajTable.getColumnModel().getColumn(0).setPreferredWidth(55);
        quajTable.getColumnModel().getColumn(0).setResizable(false);
        quajTable.getColumnModel().getColumn(1).setPreferredWidth(54);
        quajTable.getColumnModel().getColumn(1).setResizable(false);
        quajTable.getColumnModel().getColumn(2).setPreferredWidth(55);
        quajTable.getColumnModel().getColumn(2).setResizable(false);
        quajTable.getColumnModel().getColumn(3).setPreferredWidth(55);
        quajTable.getColumnModel().getColumn(3).setResizable(false);
        quajTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
           
        quijTable.setModel(new ModeloTabela(dadosqui, colunas));      
        quijTable.getColumnModel().getColumn(0).setPreferredWidth(55);
        quijTable.getColumnModel().getColumn(0).setResizable(false);
        quijTable.getColumnModel().getColumn(1).setPreferredWidth(54);
        quijTable.getColumnModel().getColumn(1).setResizable(false);
        quijTable.getColumnModel().getColumn(2).setPreferredWidth(55);
        quijTable.getColumnModel().getColumn(2).setResizable(false);
        quijTable.getColumnModel().getColumn(3).setPreferredWidth(55);
        quijTable.getColumnModel().getColumn(3).setResizable(false);
        quijTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
          
        sexjTable.setModel(new ModeloTabela(dadosSex, colunas));      
        sexjTable.getColumnModel().getColumn(0).setPreferredWidth(55);
        sexjTable.getColumnModel().getColumn(0).setResizable(false);
        sexjTable.getColumnModel().getColumn(1).setPreferredWidth(54);
        sexjTable.getColumnModel().getColumn(1).setResizable(false);
        sexjTable.getColumnModel().getColumn(2).setPreferredWidth(55);
        sexjTable.getColumnModel().getColumn(2).setResizable(false);
        sexjTable.getColumnModel().getColumn(3).setPreferredWidth(55);
        sexjTable.getColumnModel().getColumn(3).setResizable(false);
        sexjTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        
        sabjTable.setModel(new ModeloTabela(dadosSab, colunas));      
        sabjTable.getColumnModel().getColumn(0).setPreferredWidth(55);
        sabjTable.getColumnModel().getColumn(0).setResizable(false);
        sabjTable.getColumnModel().getColumn(1).setPreferredWidth(54);
        sabjTable.getColumnModel().getColumn(1).setResizable(false);
        sabjTable.getColumnModel().getColumn(2).setPreferredWidth(55);
        sabjTable.getColumnModel().getColumn(2).setResizable(false);
        sabjTable.getColumnModel().getColumn(3).setPreferredWidth(55);
        sabjTable.getColumnModel().getColumn(3).setResizable(false);
        sabjTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
           
        domjTable.setModel(new ModeloTabela(dadosDom, colunas));      
        domjTable.getColumnModel().getColumn(0).setPreferredWidth(55);
        domjTable.getColumnModel().getColumn(0).setResizable(false);
        domjTable.getColumnModel().getColumn(1).setPreferredWidth(54);
        domjTable.getColumnModel().getColumn(1).setResizable(false);
        domjTable.getColumnModel().getColumn(2).setPreferredWidth(55);
        domjTable.getColumnModel().getColumn(2).setResizable(false);
        domjTable.getColumnModel().getColumn(3).setPreferredWidth(55);
        domjTable.getColumnModel().getColumn(3).setResizable(false);
        domjTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    }
    
    public void gerarPDF(){
        Document doc = new Document();
         try {
            
            PdfWriter.getInstance(doc, new FileOutputStream("Ficha de treino "+ficha.getAluno().getNome()+
                    " nº"+ficha.getId()+".pdf"));
            doc.setPageSize(PageSize.A4.rotate());
            Font fontCab = new Font(Font.FontFamily.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLACK);
            Font fontTexto = new Font(Font.FontFamily.TIMES_ROMAN,12,Font.NORMAL,BaseColor.BLACK);
            
            PdfPTable tabela = new PdfPTable(3);
            PdfPTable tabela2 = new PdfPTable(2);
            PdfPTable tabela3 = new PdfPTable(2);
            PdfPTable segunda = new PdfPTable(4);
            PdfPTable terca = new PdfPTable(4);
            PdfPTable quarta = new PdfPTable(4);
            PdfPTable quinta = new PdfPTable(4);
            PdfPTable sexta = new PdfPTable(4);
            PdfPTable sabado = new PdfPTable(4);
            PdfPTable domingo = new PdfPTable(4);
            
            segunda.addCell(new Paragraph("Exercício  ", fontTexto));
            segunda.addCell(new Paragraph("Série  ", fontTexto));
            segunda.addCell(new Paragraph("Rep.", fontTexto));
            segunda.addCell(new Paragraph("Observação   ", fontTexto));

            for(FichaExercicio a: seg){
                segunda.addCell(new Paragraph(""+a.getExercicio().getNome(), fontTexto));
                segunda.addCell(new Paragraph(""+a.getSerie(), fontTexto));                
                segunda.addCell(new Paragraph(""+a.getRepeticoes(), fontTexto));
                segunda.addCell(new Paragraph(""+a.getObs(), fontTexto));
            }
            
            terca.addCell(new Paragraph("Exercício  ", fontTexto));
            terca.addCell(new Paragraph("Série  ", fontTexto));
            terca.addCell(new Paragraph("Rep.", fontTexto));
            terca.addCell(new Paragraph("Observação   ", fontTexto));

            for(FichaExercicio a: ter){
                terca.addCell(new Paragraph(""+a.getExercicio().getNome(), fontTexto));
                terca.addCell(new Paragraph(""+a.getSerie(), fontTexto));                
                terca.addCell(new Paragraph(""+a.getRepeticoes(), fontTexto));
                terca.addCell(new Paragraph(""+a.getObs(), fontTexto));
            }
            
            quarta.addCell(new Paragraph("Exercício  ", fontTexto));
            quarta.addCell(new Paragraph("Série  ", fontTexto));
            quarta.addCell(new Paragraph("Rep.", fontTexto));
            quarta.addCell(new Paragraph("Observação   ", fontTexto));

            for(FichaExercicio a: qua){
                quarta.addCell(new Paragraph(""+a.getExercicio().getNome(), fontTexto));
                quarta.addCell(new Paragraph(""+a.getSerie(), fontTexto));                
                quarta.addCell(new Paragraph(""+a.getRepeticoes(), fontTexto));
                quarta.addCell(new Paragraph(""+a.getObs(), fontTexto));
            }
            
            quinta.addCell(new Paragraph("Exercício  ", fontTexto));
            quinta.addCell(new Paragraph("Série  ", fontTexto));
            quinta.addCell(new Paragraph("Rep.", fontTexto));
            quinta.addCell(new Paragraph("Observação   ", fontTexto));

            for(FichaExercicio a: qui){
                quinta.addCell(new Paragraph(""+a.getExercicio().getNome(), fontTexto));
                quinta.addCell(new Paragraph(""+a.getSerie(), fontTexto));                
                quinta.addCell(new Paragraph(""+a.getRepeticoes(), fontTexto));
                quinta.addCell(new Paragraph(""+a.getObs(), fontTexto));
            }
            
            sexta.addCell(new Paragraph("Exercício  ", fontTexto));
            sexta.addCell(new Paragraph("Série  ", fontTexto));
            sexta.addCell(new Paragraph("Rep.", fontTexto));
            sexta.addCell(new Paragraph("Observação   ", fontTexto));

            for(FichaExercicio a: sex){
                sexta.addCell(new Paragraph(""+a.getExercicio().getNome(), fontTexto));
                sexta.addCell(new Paragraph(""+a.getSerie(), fontTexto));                
                sexta.addCell(new Paragraph(""+a.getRepeticoes(), fontTexto));
                sexta.addCell(new Paragraph(""+a.getObs(), fontTexto));
            }
            
            sabado.addCell(new Paragraph("Exercício  ", fontTexto));
            sabado.addCell(new Paragraph("Série  ", fontTexto));
            sabado.addCell(new Paragraph("Rep.", fontTexto));
            sabado.addCell(new Paragraph("Observação   ", fontTexto));

            for(FichaExercicio a: sab){
                sabado.addCell(new Paragraph(""+a.getExercicio().getNome(), fontTexto));
                sabado.addCell(new Paragraph(""+a.getSerie(), fontTexto));                
                sabado.addCell(new Paragraph(""+a.getRepeticoes(), fontTexto));
                sabado.addCell(new Paragraph(""+a.getObs(), fontTexto));
            }
            
            domingo.addCell(new Paragraph("Exercício  ", fontTexto));
            domingo.addCell(new Paragraph("Série  ", fontTexto));
            domingo.addCell(new Paragraph("Rep.", fontTexto));
            domingo.addCell(new Paragraph("Observação   ", fontTexto));

            for(FichaExercicio a: dom){
                domingo.addCell(new Paragraph(""+a.getExercicio().getNome(), fontTexto));
                domingo.addCell(new Paragraph(""+a.getSerie(), fontTexto));                
                domingo.addCell(new Paragraph(""+a.getRepeticoes(), fontTexto));
                domingo.addCell(new Paragraph(""+a.getObs(), fontTexto));
            }
            
            tabela.addCell("Segunda");
            tabela.addCell("Terça");
            tabela.addCell("Quarta");
            tabela2.addCell("Quinta");
            tabela2.addCell("Sexta");
            tabela3.addCell("Sabado");
            tabela3.addCell("Domingo");
            
            
            tabela.addCell(segunda);
            tabela.addCell(terca);
            tabela.addCell(quarta);
            tabela2.addCell(quinta);
            tabela2.addCell(sexta);
            tabela3.addCell(sabado);
            tabela3.addCell(domingo);
            
            
            doc.open();            
            doc.add(new Paragraph(Util.getDatasRel(new java.util.Date()),fontTexto));
            doc.add(new Paragraph("GYM - Ficha de Treino "+ficha.getAluno().getNome()+
            " nº"+ficha.getId()+"\n\n",fontCab));
//            doc.add(new Paragraph("\n          Segunda\n\n",fontTexto));
//            doc.add(segunda);
//            doc.add(new Paragraph("\n          Terça\n\n",fontTexto));
//            doc.add(terca);
//            doc.add(new Paragraph("\n          Quarta\n\n",fontTexto));
//            doc.add(quarta);
//            doc.add(new Paragraph("\n          Quinta\n\n",fontTexto));
//            doc.add(quinta);
//            doc.add(new Paragraph("\n          Sexta\n\n",fontTexto));
//            doc.add(sexta);
//            doc.add(new Paragraph("\n          Sabado\n\n",fontTexto));
//            doc.add(sabado);
//            doc.add(new Paragraph("\n          Domingo\n\n\n",fontTexto));
//            doc.add(domingo);
            doc.add(tabela);
            doc.add(tabela2);
            doc.add(tabela3);
        } catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(RelatoriListaFunJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            doc.close();
        }
        
        try {
            Desktop.getDesktop().open(new File("Ficha de treino "+ficha.getAluno().getNome()+
                    " nº"+ficha.getId()+".pdf"));
        } catch (IOException ex) {
            Logger.getLogger(RelatoriListaFunJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    public JPanel getjPaneTreino() {
        return jPaneTreino;
    }

    public JPanel getjPanelDetalhes() {
        return jPanelDetalhes;
    }
    
    

}